# These are supported funding model platforms

github: mrz1836
custom: https://mrz1818.com/?tab=tips&utm_source=github&utm_medium=sponsor-link&utm_campaign=codepipeline-to-github&utm_term=codepipeline-to-github&utm_content=codepipeline-to-github
