version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo ${CODEBUILD_SOURCE_REPO_URL}
      - echo ${CODEBUILD_SOURCE_VERSION}
      - echo ${CODEBUILD_WEBHOOK_BASE_REF}
      - echo ${CODEBUILD_WEBHOOK_EVENT}
      - echo ${CODEBUILD_WEBHOOK_PREV_COMMIT}
      - echo ${CODEBUILD_WEBHOOK_PREV_COMMIT}
      - echo ${CODEBUILD_WEBHOOK_HEAD_REF}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
  build:
    commands:
      - |
        if [ ${CODEBUILD_BUILD_NUMBER} -gt "1" ] ; then
          echo "Starting to deploy build #${CODEBUILD_BUILD_NUMBER}"
          make deploy
        fi